{
 "title": "Solar",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Power Output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max_over_time({filename=\"/var/log/solar.metric\"} |= `p1` | logfmt | unwrap p1 | __error__=\"\" [5m]) by (instance)",
     "legendFormat": "Panel 1"
    },
    {
     "expr": "max_over_time({filename=\"/var/log/solar.metric\"} |= `p2` | logfmt | unwrap p2 | __error__=\"\" [5m]) by (instance)",
     "legendFormat": "Panel 2"
    }
   ]
  },
  {
   "title": "Power Output by Panel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max_over_time({filename=\"/var/log/solar.metric\"} |= `p1` | logfmt | unwrap p1 | __error__=\"\" [5m]) by (instance)",
     "legendFormat": "Panel 1"
    },
    {
     "expr": "max_over_time({filename=\"/var/log/solar.metric\"} |= `p2` | logfmt | unwrap p2 | __error__=\"\" [5m]) by (instance)",
     "legendFormat": "Panel 2"
    }
   ]
  },
  {
   "title": "PV Info",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "{filename=\"/var/log/solar.metric\"} | logfmt"
    }
   ]
  },
  {
   "title": "Total Power Output per Day",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum by (instance) (sum_over_time({filename=\"/var/log/solar.metric\"} |= \"p1\" | logfmt | __error__ = \"\" | unwrap p1 [24h])) / 24",
     "legendFormat": "Panel1"
    },
    {
     "expr": "sum by (instance) (sum_over_time({filename=\"/var/log/solar.metric\"} |= \"p2\" | logfmt | __error__ = \"\" | unwrap p2 [24h])) / 24",
     "legendFormat": "Panel2"
    }
   ]
  }
 ]
}